#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# Migration guard: never remove legacy test modules unless the full overlay
# has already been extracted in the correct project root.
new_modules=(
  "tests/admin/test_analytics.py"
  "tests/admin/test_operations.py"
  "tests/admin/test_permissions.py"
  "tests/admin/test_project_docs.py"
  "tests/admin/test_usage_entitlements.py"
  "tests/adventures/test_adventures.py"
  "tests/adventures/test_challenge_scaling.py"
  "tests/adventures/test_gameplay_regressions.py"
  "tests/adventures/test_history.py"
  "tests/adventures/test_intermissions.py"
  "tests/adventures/test_launch_story.py"
  "tests/adventures/test_micro_events.py"
  "tests/adventures/test_qte_levelup.py"
  "tests/adventures/test_recovery.py"
  "tests/adventures/test_runtime_budget.py"
  "tests/adventures/test_ui_contract.py"
  "tests/arcade/test_catalog.py"
  "tests/arcade/test_feedback.py"
  "tests/arcade/test_geometry_depth.py"
  "tests/arcade/test_modes_projectiles.py"
  "tests/arcade/test_pacing.py"
  "tests/arcade/test_physics_readability.py"
  "tests/auth/test_datetime_compat.py"
  "tests/auth/test_permissions.py"
  "tests/authoring/test_ai_assist.py"
  "tests/authoring/test_authoring.py"
  "tests/authoring/test_portability.py"
  "tests/authoring/test_ui.py"
  "tests/authoring/test_world_scoping.py"
  "tests/director/test_ascii_art.py"
  "tests/director/test_generation.py"
  "tests/director/test_pacing.py"
  "tests/director/test_parallel_recap.py"
  "tests/director/test_runtime.py"
  "tests/director/test_schema.py"
  "tests/director/test_synopsis.py"
  "tests/frontend/test_account_center.py"
  "tests/frontend/test_onboarding.py"
  "tests/frontend/test_player_library.py"
  "tests/frontend/test_public_shell.py"
  "tests/frontend/test_visual_hierarchy.py"
  "tests/heroes/test_character_system.py"
  "tests/heroes/test_history_postgres.py"
  "tests/heroes/test_progression.py"
  "tests/heroes/test_ui_contract.py"
  "tests/multiplayer/test_invites.py"
  "tests/multiplayer/test_notifications.py"
  "tests/multiplayer/test_partner_notifications.py"
  "tests/multiplayer/test_party_gate.py"
  "tests/multiplayer/test_rooms.py"
  "tests/multiplayer/test_sharing_social.py"
  "tests/persistence/test_database_compat.py"
  "tests/persistence/test_postgres_wiring.py"
)
for module in "${new_modules[@]}"; do
    if [[ ! -s "$module" ]]; then
        echo "ERROR: expected new test missing or empty: $module" >&2
        echo "Extract the Pass 50 overlay at the project root before cleanup." >&2
        exit 1
    fi
done

removed=0
legacy_modules=(
  "tests/test_admin_analytics.py"
  "tests/test_admin_permissions.py"
  "tests/test_admin_project_docs.py"
  "tests/test_adventure_history.py"
  "tests/test_adventures.py"
  "tests/test_arcade_pacing_pass29.py"
  "tests/test_ascii_art_pipeline.py"
  "tests/test_auth_datetime_compat.py"
  "tests/test_auth_permissions.py"
  "tests/test_author_ai_assist.py"
  "tests/test_author_ui.py"
  "tests/test_authoring.py"
  "tests/test_challenge_scaling.py"
  "tests/test_character_progression.py"
  "tests/test_character_system_v2.py"
  "tests/test_character_ui_contract.py"
  "tests/test_content_portability.py"
  "tests/test_database_compat.py"
  "tests/test_director_pacing.py"
  "tests/test_director_parallel_recap.py"
  "tests/test_director_runtime.py"
  "tests/test_director_schema.py"
  "tests/test_gameplay_ui_contract.py"
  "tests/test_generation.py"
  "tests/test_generation_synopsis.py"
  "tests/test_hero_history_postgres_fix.py"
  "tests/test_intermission_variety.py"
  "tests/test_invite_flow_contract.py"
  "tests/test_micro_events.py"
  "tests/test_partner_notifications.py"
  "tests/test_pass31_story_qte_levelup.py"
  "tests/test_pass32_multiplayer_sharing_social.py"
  "tests/test_pass33_real_notifications.py"
  "tests/test_pass34_arcade_expansion.py"
  "tests/test_pass35_visual_hierarchy.py"
  "tests/test_pass36_arcade_juice.py"
  "tests/test_pass37_arcade_physics_readability.py"
  "tests/test_pass38_arcade_modes_projectile_variety.py"
  "tests/test_pass38i_arcade_geometry_depth.py"
  "tests/test_pass39_author_scope.py"
  "tests/test_pass40_launch_story_polish.py"
  "tests/test_pass41_story_runtime_budget.py"
  "tests/test_pass42_account_center.py"
  "tests/test_pass43_gameplay_hotfix.py"
  "tests/test_pass43_usage_entitlements.py"
  "tests/test_pass44_player_library.py"
  "tests/test_pass45_onboarding.py"
  "tests/test_pass46_operations.py"
  "tests/test_postgres_store_wiring.py"
  "tests/test_public_shell_pass29b.py"
  "tests/test_room_party_gate.py"
  "tests/test_rooms.py"
  "tests/test_runtime_recovery_pass20.py"
)
for legacy in "${legacy_modules[@]}"; do
    if [[ -f "$legacy" ]]; then
        rm -- "$legacy"
        ((removed+=1))
    fi
done

echo "Pass 50 test layout applied: ${#new_modules[@]} relocated modules verified; $removed old copies removed."
echo "You can now run: ./scripts/release-staging.sh "Pass 50: organize regression tests by feature""
